#!/usr/bin/env perl
use strict;
use Dist::Iller::App;

our $VERSION = '0.1101'; # VERSION
# PODNAME: iller

Dist::Iller::App->run;

__END__

=pod

=encoding UTF-8

=head1 NAME

iller

=head1 VERSION

version 0.1101

=head1 AUTHOR

Erik Carlsson <info@code301.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2015 by Erik Carlsson.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
